name: Test

permissions:
  id-token: write
  contents: write

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "branch=testtest" >> $GITHUB_OUTPUT
        id: step1

      - name: Print extract
        shell: bash
        run: echo ${{ steps.step1.outputs.branch }}
          
